services:
  dashboard:
    build: .
    container_name: ubuntu-monitor
    network_mode: "host" # Required to see host network stats
    pid: "host"          # Required to see host processes and true CPU/RAM
    environment:
      - PORT=${PORT:-8081}
    volumes:
      - /proc:/proc:ro
      - /sys:/sys:ro
      - /dev:/dev:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  cloudflared_orbitalmetrics:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel-orbital
    network_mode: "host"
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_API_TOKEN}
    restart: unless-stopped
